### ISSUE TITLE
Reconsider the "For Humans" mantle

### ISSUE THREAD

**Issue by coleifer** [jjangsangy/ExplainToMe#1]
I wrote a short piece on my issues with projects that label themselves _For Humans_ . You can find the full version [here](http://charlesleifer.com/blog/describing-projects-as-for-humans-must-stop/).

Your awesome project did a good job summarizing, though, so I'll just paste the summary:

> When Kenneth Reitz created the requests library, the Python community rushed to embrace the project, as it provided (finally) a clean, sane API for making HTTP requests.
> 
> He subtitled his project "Python HTTP Requests for Humans", referring, I suppose, to the fact that his API provided developer-friendly APIs.
> 
> If naming things "for humans" had stopped there, that would have been fine with me, but instead there's been a steady stream of new projects describing themselves as being "For Humans" and I have issues with that.
> 
> When a new project comes out describing itself as X for humans , it somehow implies that any other libraries existing in the X space before were somehow not for humans.
> 
> To call your project For Humans is just a pretentious way of saying that you see your project as having a superior API to other projects in the same space.
> 
> So many projects have taken up the for humans mantle that can it really be said to mean anything anymore?
> 
> records , "SQL for Humans" legit , "Git for Humans" pep8 , "pep8 for Humans" hypermark , "markdown for Humans"
> 
> If your project has an awesome API, then say that instead.
> 
> If your project is an improvement over other projects in the space, then tell us why.
> 
> But just labeling your project for humans is both disrespectful and honestly a bit cringe-worthy.

Fantastic work on the project :)

**Comment by jjangsangy** [comment]
I'm actually not very partial with the "for humans" moniker either. I'll definitely consider replacing it once I can think of a suitable replacement. Definitely appreciate your input, I'm a big fan of peewee!

**Comment by coleifer** [comment]
Thanks, I'm flattered that you've heard of peewee!

**Comment by jjangsangy** [comment]
Tagline has been changed so closing this.
