### ISSUE TITLE
JSON API always uses default values, ignoring actual values

### ISSUE THREAD

**Issue by Cloudmersive** [jjangsangy/ExplainToMe#13]
For example:

curl -X POST "https://explaintome.herokuapp.com/api/v1.0/summary" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"url\": \"https://www.technologyreview.com/s/513696/deep-learning/\", \"max_sent\": 0}"

Actually returns the default Wall Street Journal article defined in the code.

**Comment by jjangsangy** [comment]
Thanks for catching this example. I've updated the api definition on swagger and so everything works.

```python
curl -X POST "https://explaintome-app.herokuapp.com/api/v1.1.1/summary" \
    -H "accept: application/json" \
    -H "Content-Type: application/json" \
    -d '{ "max_sent": 10, "url": "https://www.technologyreview.com/s/513696/deep-learning/"}'
```
